### ISSUE TITLE
Phasing not resetting

### ISSUE THREAD

**Issue by NinesCC** [Nyeriah/mod-instanced-worldbosses#4]
![image](https://github.com/Nyeriah/mod-instanced-worldbosses/assets/123340833/474851dd-1797-4935-ae77-bdb9b99f4e8a)
![image](https://github.com/Nyeriah/mod-instanced-worldbosses/assets/123340833/c592864e-876f-4cf3-9dad-10fe173c19c9)
![image](https://github.com/Nyeriah/mod-instanced-worldbosses/assets/123340833/2eac9cff-75f7-4032-8dfb-95ed756037aa)

Tested on two different characters that haven't interacted with these bosses for more than 10 days. Characters continue to be saved.

**Comment by Nyeriah** [comment]
Doesn't seem like this is the case at all anymore? @Samsequel

**Comment by Samsequel** [comment]
Not that I know off

**Comment by Nyeriah** [comment]
Okay I'll be closing it then. Dunno what happened here
